openapi: 3.0.3
info:
  title: ChargeMe
  description: ChargeMe
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1

paths:
  /healthz:
    get:
      tags:
        - technical
      summary: Проверка сервиса
      description: >-
        Проверка сервиса на работоспособность
      operationId: healthCheck
      responses:
        '200':
          description: Сервис работает

  /v1/locations:
    get:
      tags:
        - locations with stations
      operationId: getLocations
      summary: Получение списка локаций с зарядками в пределах координат.
      description: Получение списка локаций с зарядками в пределах координат.
      parameters:
        - name: latitudeMin
          in: query
          schema:
            description: >-
              Широта правого нижнего угла.
            type: number
            example: 56.432
        - name: longitudeMin
          in: query
          schema:
            description: >-
              Долгота правого нижнего угла.
            type: number
            example: 56.432
        - name: latitudeMax
          in: query
          schema:
            description: >-
              Широта правого верхнего угла.
            type: number
            example: 56.432
        - name: longitudeMax
          in: query
          schema:
            description: >-
              Долгота правого верхнего угла.
            type: number
            example: 65.432
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseLocations'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/locations/stations:
    get:
      tags:
        - charging stations on location
      operationId: getChargingStations
      summary: Получение списка зарядных станций и удобств на локации.
      description: Получение списка зарядных станций и удобств на локации.
      parameters:
        - name: locationId
          required: true
          in: query
          schema:
            description: >-
              Идентификатор локации.
            type: string
            example: "1234"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStations'


components:
  schemas:
    ResponseLocations:
      type: object
      required:
        - locations
      properties:
        locations:
          type: array
          description: Результат запроса.
          items:
            $ref: '#/components/schemas/AddressStationsPreliminary'

    AddressStationsPreliminary:
      description: Список станций по адресу
      type: object
      required:
        - access
        - address
        - id
        - latitude
        - longitude
        - name
        - stations
      properties:
        access:
          type: integer
        address:
          type: string
        icon:
          type: string
        icon_type:
          type: string
        id:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        name:
          type: string
        score:
          type: number
        stations:
          type: array
          items:
            $ref: '#/components/schemas/StationPreliminary'

    StationPreliminary:
      description: Сущность станции.
      type: object
      required:
        - id
        - outlets
      properties:
        id:
          type: string
        outlets:
          type: array
          items:
            $ref: '#/components/schemas/OutletPreliminary'

    OutletPreliminary:
      description: Сущность разъема.
      type: object
      required:
        - connector
        - id
        - power
      properties:
        connector:
          type: integer
        id:
          type: string
        kilowatts:
          type: number
          nullable: true
        power:
          type: integer

    ResponseStations:
      type: object
      required:
        - location
        - reviews
        - amenities
      properties:
        location:
            $ref: '#/components/schemas/AddressStationsFull'
        reviews:
          type: array
          description: Отзывы о локации
          items:
            $ref: '#/components/schemas/Review'
        amenities:
          type: array
          description: Удобства
          items:
            $ref: '#/components/schemas/Amenity'

    AddressStationsFull:
      description: Список станций по адресу
      type: object
      required:
        - address
        - id
        - latitude
        - longitude
        - name
        - stations
      properties:
        access:
          type: integer
        address:
          type: string
        icon_type:
          type: string
        id:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        name:
          type: string
        score:
          type: number
        description:
          type: string
        access_restriction:
          type: string
        access_restriction_description:
          type: string
        cost:
          type: boolean
        cost_description:
          type: string
        hours:
          type: string
        open247:
          type: boolean
        is_open_or_active:
          type: boolean
        phone_number:
          type: string
        stations:
          type: array
          items:
            $ref: '#/components/schemas/StationFull'

    StationFull:
      description: Полная информация о станции.
      type: object
      required:
        - id
        - outlets
      properties:
        id:
          type: string
        outlets:
          type: array
          items:
            $ref: "#/components/schemas/OutletPreliminary"
        available:
          type: integer
        cost:
          type: integer
        name:
          type: string
        manufacturer:
          type: string
        cost_description:
          type: string
        hours:
          type: string
        kilowatts:
          type: number

    Review:
      description: Отзыв о локации.
      type: object
      required:
        - id
        - station_id
        - outlet_id
        - created_at
      properties:
        id:
          type: string
        station_id:
          type: string
        outlet_id:
          type: string
        comment:
          type: string
        rating:
          type: integer
        connector_type:
          type: integer
        user_name:
          type: string
        vehicle_name:
          type: string
        vehicle_type:
          type: string
        created_at:
          type: string
          format: date-time

    Amenity:
      description: Удобсва.
      type: object
      required:
        - id
        - location_id
      properties:
        id:
          type: string
        location_id:
          type: string
        form:
          type: integer

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
