openapi: 3.0.3
info:
  title: ChargeMe
  description: ChargeMe
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1

paths:
  /healthz:
    get:
      tags:
        - technical
      summary: Проверка сервиса
      description: >-
        Проверка сервиса на работоспособность
      operationId: healthCheck
      responses:
        '200':
          description: Сервис работает

  /v1/locations:
    get:
      tags:
        - locations with stations
      operationId: getLocations
      summary: Получение списка локаций с зарядками в пределах координат.
      description: Получение списка локаций с зарядками в пределах координат.
      parameters:
        - name: latitudeMin
          in: query
          schema:
            description: >-
              Широта правого нижнего угла.
            type: number
            example: 56.432
        - name: longitudeMin
          in: query
          schema:
            description: >-
              Долгота правого нижнего угла.
            type: number
            example: 56.432
        - name: latitudeMax
          in: query
          schema:
            description: >-
              Широта правого верхнего угла.
            type: number
            example: 56.432
        - name: longitudeMax
          in: query
          schema:
            description: >-
              Долгота правого верхнего угла.
            type: number
            example: 65.432
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationsOnMap'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - creating place
      summary: Создания локации со станциями.
      description: >-
        Создания локации со станциями.
      operationId: createFullLocation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationFull'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationsOnMap'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - update location
      operationId: updateLocation
      summary: Обновление станции по идентификатору.
      description: Обновление станции по идентификатору.
      parameters:
        - name: locationId
          required: true
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationFull'
      responses:
        '200':
          description: Success
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



  /v1/locations/stations:
    get:
      tags:
        - charging stations on location
      operationId: getChargingStationsByLocationID
      summary: Получение списка зарядных станций и удобств на локации.
      description: Получение списка зарядных станций и удобств на локации.
      parameters:
        - name: locationId
          required: true
          in: query
          schema:
            description: >-
              Идентификатор локации.
            type: string
            example: "1234"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationFull'

  /v1/review:
    post:
      tags:
        - create review
      operationId: createReview
      summary: Создание ревью.
      description: Создание ревью.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReview"
      responses:
        '200':
          description: success
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /v1/checkin:
    post:
      tags:
        - create checkin
      operationId: createCheckin
      summary: Создание чекина.
      description: Создание чекина.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckinCreate"
      responses:
        '200':
          description: success
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /v1/auth:
    post:
      tags:
        - authentication with apple
      operationId: authenticate
      summary: Аутентификация с помощью AppleId.
      description: Аутентификация с помощью AppleId.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/user/{userId}:
    parameters:
      - name: userId
        required: true
        in: path
        schema:
          type: string
    get:
      tags:
        - get user by id.
      operationId: getUserByUserId
      summary: Получение польной информации о юзере по идентификатору.
      description: Получение польной информации о юзере по идентификатору.
      responses:
        '200':
          description: Successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/user/vehicle:
    post:
      tags:
        - add user's vehicle
      operationId: addVehicle
      summary: Добавление автомобиля пользователя.
      description: Добавление автомобиля пользователя.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VehicleWithUserId"
      responses:
        '200':
          description: success
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    SignInRequest:
      type: object
      required:
        - user_identifier
        - sign_type
      properties:
        sign_type:
          type: string
        photo_url:
          type: string
        display_name:
          type: string
        email:
          type: string
        user_identifier:
          type: string
        apple_credentials:
          $ref: "#/components/schemas/AppleAuthCredentials"
        google_credentials:
          $ref: "#/components/schemas/GoogleAuthCredentials"


    AppleAuthCredentials:
      type: object
      required:
        - authorization_code
        - identity_token
      properties:
        authorization_code:
          type: string
        identity_token:
          type: string

    GoogleAuthCredentials:
      type: object
      required:
        - id_token
        - access_token
      properties:
        id_token:
          type: string
        access_token:
          type: string

    LocationsOnMap:
      type: object
      required:
        - locations
      properties:
        locations:
          type: array
          description: Результат запроса.
          items:
            $ref: '#/components/schemas/LocationPreliminary'

    LocationPreliminary:
      description: Список станций по адресу
      type: object
      required:
        - address
        - id
        - latitude
        - longitude
        - name
        - stations
        - icon_type
      properties:
        access:
          type: integer
        address:
          type: string
        icon:
          type: string
        icon_type:
          type: string
        id:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        name:
          type: string
        score:
          type: number
        stations:
          type: array
          items:
            $ref: '#/components/schemas/StationPreliminary'

    VehicleWithUserId:
      description: Сущность автомобиля
      type: object
      required:
        - user_id
        - vehicle_type
      properties:
        user_id:
          type: string
        vehicle_type:
          type: integer

    Vehicle:
      description: Сущность автомобиля
      type: object
      required:
        - vehicle_type
      properties:
        vehicle_type:
          type: integer

    CheckinCreate:
      description: Сущность чекина для создания.
      type: object
      required:
        - user_id
        - station_id
        - outlet_id
        - rating
        - duration
        - user_name
      properties:
        user_id:
          type: string
        station_id:
          type: string
        outlet_id:
          type: string
        vehicle_type:
          type: integer
        user_name:
          type: string
        comment:
          type: string
        kilowatts:
          type: number
        rating:
          type: integer
        duration:
          type: integer

    CheckinStation:
      description: Сущность чекина.
      type: object
      required:
        - user_id
        - station_id
        - outlet_id
        - rating
        - finishes_at
        - user_name
      properties:
        user_id:
          type: string
        station_id:
          type: string
        outlet_id:
          type: string
        vehicle_type:
          type: integer
        user_name:
          type: string
        comment:
          type: string
        kilowatts:
          type: number
        rating:
          type: integer
        finishes_at:
          type: string
          format: date-time
          description: Время окончания зарядки в UTC

    StationPreliminary:
      description: Сущность станции.
      type: object
      required:
        - id
        - outlets
      properties:
        id:
          type: string
        outlets:
          type: array
          items:
            $ref: '#/components/schemas/Outlet'

    Outlet:
      description: Сущность разъема.
      type: object
      required:
        - connector
        - id
        - power
      properties:
        connector:
          type: integer
        id:
          type: string
        kilowatts:
          type: number
          nullable: true
        power:
          type: integer
        price:
          type: number
          nullable: true

    LocationWithFullStation:
      type: object
      required:
        - location
        - reviews
        - amenities
      properties:
        location:
          $ref: '#/components/schemas/LocationFull'
        reviews:
          type: array
          description: Отзывы о локации
          items:
            $ref: '#/components/schemas/Review'
        amenities:
          type: array
          description: Удобства
          items:
            $ref: '#/components/schemas/Amenity'

    LocationFull:
      description: Список станций по адресу
      type: object
      required:
        - address
        - id
        - latitude
        - longitude
        - name
        - stations
        - icon_type
      properties:
        photos:
          type: array
          items:
            $ref: '#/components/schemas/Photo'
        access:
          type: integer
        address:
          type: string
        icon_type:
          type: string
        id:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        name:
          type: string
        score:
          type: number
        description:
          type: string
        cost:
          type: boolean
        cost_description:
          type: string
        hours:
          type: string
        open247:
          type: boolean
        coming_soon:
          type: boolean
        phone_number:
          type: string
        stations:
          type: array
          items:
            $ref: '#/components/schemas/StationFull'
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'
        amenities:
          type: array
          items:
            $ref: '#/components/schemas/Amenity'

    Photo:
      required:
        - id
        - url
        - user_id
        - created_at
      properties:
        id:
          type: string
        url:
          type: string
        user_id:
          type: string
        caption:
          type: string
        created_at:
          type: string
          format: date-time

    StationFull:
      description: Полная информация о станции.
      type: object
      required:
        - id
        - outlets
      properties:
        id:
          type: string
        outlets:
          type: array
          items:
            $ref: "#/components/schemas/Outlet"
        available:
          type: integer
        cost:
          type: integer
        name:
          type: string
        manufacturer:
          type: string
        cost_description:
          type: string
        hours:
          type: string
        kilowatts:
          type: number
        checkin:
          $ref: '#/components/schemas/CheckinStation'

    Review:
      description: Отзыв о локации.
      type: object
      required:
        - id
        - station_id
        - outlet_id
        - created_at
      properties:
        id:
          type: string
        station_id:
          type: string
        outlet_id:
          type: string
        comment:
          type: string
        rating:
          type: integer
        connector_type:
          type: integer
        kilowatts:
          type: number
        user_name:
          type: string
        vehicle_name:
          type: string
        vehicle_type:
          type: integer
        created_at:
          type: string
          format: date-time

    CreateReview:
      description: Отзыв о локации.
      type: object
      required:
        - user_id
        - user_name
        - station_id
        - outlet_id
      properties:
        user_id:
          type: string
        station_id:
          type: string
        outlet_id:
          type: string
        comment:
          type: string
        rating:
          type: integer
        kilowatts:
          type: number
        connector_type:
          type: integer
        user_name:
          type: string
        vehicle_name:
          type: string
        vehicle_type:
          type: integer

    Amenity:
      description: Удобсва.
      type: object
      required:
        - id
        - location_id
        - form
      properties:
        id:
          type: string
        location_id:
          type: string
        form:
          type: integer

    AuthResponse:
      description: ответ на авторизацию.
      type: object
      required:
        - user_id
      properties:
        user_id:
          $ref: '#/components/schemas/UserId'
        user:
          $ref: '#/components/schemas/User'

    User:
      description: Информация пользователя.
      type: object
      required:
        - display_name
        - sign_in_service
        - vehicle_type
      properties:
        id:
          type: string
        display_name:
          type: string
        photo_url:
          type: string
        sign_in_service:
          type: string
        vehicle_type:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'
        favourites:
          type: array
          items:
            type: string
        recent_places:
          type: array
          items:
            type: string
        total_reviews:
          type: integer
        photos:
          type: integer
        contacts:
          $ref: '#/components/schemas/UserContacts'
        stats:
          type: string


    UserContacts:
      description: Контакты пользователя.
      type: object
      properties:
        phone_number:
          type: string
        email:
          type: string
        telegram:
          type: string

    UserId:
      description: Идентификатор пользователя.
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
