version: '3.5'

services:
  postgres:
    container_name: postgres_chargeMe
    image: postgres
    environment:
      POSTGRES_USER: chargeme
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    restart: unless-stopped
